services:
  mvc:
    build:
      context: .
      dockerfile: MVC/Dockerfile
    environment:
      # Pour le certificat SSL
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345678
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/Cert/composecert.pfx 
      - Logging__Loglevel__Default=Debug 
      - Logging__Loglevel__Microsoft.AspNetCore=Debug
    env_file:
      - 'secrets.env'
    volumes:
      # Pour le certificat SSL
      - ./MVC/Cert:/Cert:ro 
    healthcheck:
      test: ["CMD", "curl", "-k", "https://mvc:8081/healthz"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
        - app_vlan

  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    env_file:
      - 'secrets.env'
    networks:
        - app_vlan
    depends_on:
      mvc:
        condition: service_healthy

  worker_image:
    build:
      context: .
      dockerfile: Worker_Image/Dockerfile
    env_file:
      - 'secrets.env'
    networks:
        - app_vlan
    depends_on:
      mvc:
        condition: service_healthy

  worker_content:
    build:
       context: .
       dockerfile: Worker_Content/Dockerfile
    env_file:
      - 'secrets.env'
    networks:
        - app_vlan
    depends_on:
      mvc:
        condition: service_healthy

networks:
  app_vlan:
    driver: bridge